export const name = "_lyadh_lagche_";

export const parallaxImages = [
    {   
        key:1,
        classes:'top-[60%] left-[2%] rotate-[-5deg] img1',
        src:'./images/parallax/headless_encounter_main.jpg',
        rotation:'-50'
    },
    {   
        key:2,
        classes:'top-[10%] left-[24%] rotate-[5deg] img2',
        src:'./images/parallax/mamata.jpeg',
        rotation:'-50'
    },
    {   
        key:3,
        classes:'top-[60%] left-[42%] rotate-[0deg] img3',
        src:'./images/parallax/goddess.jpg',
        rotation:'50'
    },
    {   
        key:4,
        classes:'top-[10%] left-[58%] rotate-[-5deg] img4',
        src:'./images/parallax/untitled2.jpg',
        rotation:'-50'
    },
    {   
        key:5,
        classes:'top-[60%] left-[84%] rotate-[5deg] img5',
        src:'./images/parallax/washed-out-flags.jpg',
        rotation:'360'
    },
];
export const hoverImages=[
    {
        key:1,
        src:'./images/hover/img1.jpg'
    },
    {
        key:2,
        src:'./images/hover/img2.jpg'
    },
    {
        key:3,
        src:'./images/hover/img3.jpg'
    },
    {
        key:4,
        src:'./images/hover/img4.jpg'
    },
    {
        key:5,
        src:'./images/hover/img5.jpg'
    },
    {
        key:6,
        src:'./images/hover/img6.jpg'
    },
    {
        key:7,
        src:'./images/hover/img7.jpeg'
    },
    {
        key:8,
        src:'./images/hover/img8.jpeg'
    },
    {
        key:9,
        src:'./images/hover/img9.jpg'
    },
    {
        key:10,
        src:'./images/hover/img10.jpg'
    },
    {
        key:11,
        src:'./images/hover/img11.jpeg'
    },
    {
        key:12,
        src:'./images/hover/img12.jpg'
    },
    {
        key:13,
        src:'./images/hover/img13.jpeg'
    },
    {
        key:14,
        src:'./images/hover/img14.jpg'
    },
    {
        key:15,
        src:'./images/hover/img15.jpg'
    },
    {
        key:16,
        src:'./images/hover/img16.jpeg'
    },
    {
        key:17,
        src:'./images/hover/img17.jpg'
    },
    {
        key:18,
        src:'./images/hover/img18.jpg'
    },
    {
        key:19,
        src:'./images/hover/img19.jpg'
    },
    {
        key:20,
        src:'./images/hover/img20.jpg'
    },
    {
        key:21,
        src:'./images/hover/img21.jpeg'
    },
    {
        key:22,
        src:'./images/hover/img22.jpeg'
    },
    {
        key:23,
        src:'./images/hover/img23.jpg'
    },
]
export const opacity = {
    initial:{
        opacity:1
    },
    exit:{
        opacity:0,
        transition:{
            duration:0.7
        }
    }
};
export const slideUp = {
    initial:{
        top:0
    },
    exit:{
        top:'-100vh',
        transition:{duration: 0.8, ease:[0.76, 0, 0.24, 1], delay: 0.2}

    }
}
export const footer=[
    {
        id:1,
        src:'/assets/react.png'
    },
    {
        id:2,
        src:'/assets/gsap.png'
    },
    {
        id:3,
        src:'/assets/framer.png'
    }
]